# To update additional settings create a Secret custom resource by using a command below
# oc create secret generic additional-scrape-configs --from-file=prometheus-additional.yaml
- job_name: "pushgateway"
  honor_labels: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http

