apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway-service-monitor
  labels:
    app: iot-demo
spec:
  endpoints:
    - targetPort: 9091
      interval: 30s
      honorLabels: true
  selector:
    matchLabels:
      app: pushgateway
      prometheus/type: pushgateway
